name: mbzirc
root: ./
startup_window: demo_setup
pre_window: |
  # humble
  scout_ws
  export UAV_NAMESPACE=scout
windows:
  - scout_launch:
    - ip link set up can0 type can bitrate 500000
    - ros2 launch scout_base scout_mini_omni_base.launch.py
  - mavros:
    - ros2 launch mavros px4.launch
  - estimation:
    - ros2 launch uav_ros_estimators estimator_manager.launch.py namespace:=$UAV_NAMESPACE cmd_vel_topic:=/cmd_vel mavros_imu_topic:=/mavros/imu/data mavros_gps_raw_fix_topic:=/mavros/global_position/raw/fix mavros_home_topic:=/mavros/home_position/home
  - camera_lidar:
      layout: vertical
      panes:
        - ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true
        - ros2 launch livox_ros_driver2 rviz_MID360_launch.py
  - teleop:
      layout: vertical
      panes:
        - ros2 topic echo /scout/main/odometry | grep -A 20 pose
        - ros2 run teleop_twist_keyboard teleop_twist_keyboard _refresh_rate:=50.0
  - tf:
      layout: vertical
      panes:
        - ros2 run tf2_ros static_transform_publisher 0.375 -0.05 -0.07 0 0 0 base_link camera_link
        - ros2 run tf2_ros static_transform_publisher 0.34 -0.045 0 -1.57 0 -0.7854 base_link livox_frame
  - yolo:
      layout: vertical
      panes:
        - ros2 run img_segment segment_node
        - ros2 run pointcloud_segmentation pointcloud_segmentation
  - pointcloud_laser:
    - ros2 launch pointcloud_to_laserscan sample_pointcloud_to_laserscan_launch.py
  - slam:
    - ros2 launch slam_toolbox online_async_launch.py
  - nav:
    - ros2 launch nav2_bringup navigation_launch.py
