
gps_fix_throttle_period: 0.0
gps_fix_delay: 0.0
gps_fix_mean: 0.0
gps_fix_stddev: 0.0
R_variable: false

valid_estimators:
  heading:    ["ODOM", "IMU", "IMU", "MOVELLA", "MOVELLA"]
  horizontal: ["ODOM", "IMU", "GPS", "MOVELLA", "AR_TAG"]
  height:     ["BARO", "BARO", "BARO", "BARO", "BARO"]

agv_specific:
  gps_R_hor_moving: [1.0, 0.0,
        0.0, 1.0]
  gps_R_hor_stationary: [100000.0, 0.0,
        0.0, 100000.0]
  rotating_R_scaling: 1.0
  enable_zupt: true
