gps_fix_throttle_period: 0.0
gps_fix_delay: 0.0
gps_fix_mean: 0.0
gps_fix_stddev: 0.0
R_variable: false

valid_estimators:
  heading:    ["ODOM", "IMU"]
  horizontal: ["ODOM", "IMU"]
  height:     ["BARO", "BARO"]
